import ProjectDescription

let tests = TargetReference.project(path: "..", target: "TheoryDiagramsUnitTests")

let workspace = Workspace(
  name: "SpiralOfFifthsDemo",
  projects: ["."],
  schemes: [
    .scheme(
      name: "TheoryDiagramsUnitTests",
      buildAction: .buildAction(targets: [tests]),
      testAction: .targets(
        [.testableTarget(target: tests)],
        options: .options(coverage: true, codeCoverageTargets: [.project(path: "..", target: "TheoryDiagrams")])
      )
    )
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
