import ProjectDescription

let workspace = Workspace(
  name: "TheoryDiagrams",
  projects: [".", "Example"],
  generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)
